---

- name: Configure HTTP header security
  hosts: linux
  become: yes
  tasks:
    - name: Install the Apache HTTP server
      yum:
        name: httpd
        state: present

    - name: Ensure the Apache HTTP server is running
      service:
        name: httpd
        state: started

    - name: Set the ServerTokens directive to "Prod"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(ServerTokens) .*'
        line: 'ServerTokens Prod'
        state: present

    - name: Set the ServerSignature directive to "Off"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(ServerSignature) .*'
        line: 'ServerSignature Off'
        state: present

    - name: Set the X-Frame-Options header to "SAMEORIGIN"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(Header always) .*'
        line: 'Header always set X-Frame-Options "SAMEORIGIN"'
        state: present

    - name: Set the X-XSS-Protection header to "1; mode=block"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(Header always) .*'
        line: 'Header always set X-XSS-Protection "1; mode=block"'
        state: present

    - name: Set the X-Content-Type-Options header to "nosniff"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(Header always) .*'
        line: 'Header always set X-Content-Type-Options "nosniff"'
        state: present

    - name: Set the Strict-Transport-Security header
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(Header always) .*'
        line: 'Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"'
        state: present

    - name: Restart the Apache HTTP server
      service:
        name: httpd
        state: restarted
