---
- hosts: all
  tasks:
    - name: Install Apache HTTP Server
      package:
        name: httpd
        state: present

    - name: Update Apache HTTP Server configuration
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80$'
        line: 'Listen 8080'

    - name: Restart Apache HTTP Server
      service:
        name: httpd
        state: restarted
